### PR TITLE
A few fixes before launch!

### LINKED ISSUE #11: Improve favicons
We have a nice colour changing SVG but that's not wholly sufficient.  See https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs for details.

### PR DESCRIPTION
**Pull request by Songtech-0912**
Closes #11, #7 

So me and Siddhant talked about this in the Discord but essentially we just want to get the website launched after review. Because I am busy with school and in general I don't want to delay this any longer than we have to. I got the favicons done and I think this is good enough, the atom feed appears to work on my local testing (although not very thorough testing but we can work with that). Me and Siddhant basically agree that _whatever that isn't a dealbreaker, we can go without_, launching this 3+ year website is the more important thing. Thanks so much if you could take the time to do a review of this PR.

### CODE REVIEW

**Comment by Shrinks99** [comment]
Mostly looks great, will do a few favicon adjustements and merge!  Thanks for lighting the fire to finish it :)

**Comment by Shrinks99** [comment]
Haven't forgotten about this BTW, I have a reminder to review tomorrow :)

**Review by Shrinks99 — APPROVED** [review]
Added some improvements to the favicons (see commit messages).

Thank you for making all of these changes!  RSS does indeed seem to work (I think I was running into a cache issue). Closing #12 as a result (merged into here already)

**Comment by Songtech-0912** [comment]
You are amazing! Thank you so much! 😄

**Pull request merged**
